version: "3.7"

services:
  webapi:
    build:
      context: ./
      dockerfile: src/Checkout.PaymentGateway.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Connections__DynamoDb=http://dynamodb:8000
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=def
    ports:
      - 9002:80
    restart: always
    depends_on:
      - dynamodb
  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"