version: "3.7"

services:
  webapi:
    build:
      context: ./
      dockerfile: src/Checkout.PaymentGateway.WebApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Connections__RedisEndpoint=redis_image:6379
    ports:
      - 9001:80
    restart: always
    depends_on:
      - redis_image
  redis_image:
    image: redis
    container_name: redis_image
    ports:
      - "6379:6379"